authors:
  07prajwal2000:
    name: Prajwal Aradhya
    description: Creator of Fluxify
    avatar: https://avatars.githubusercontent.com/u/54446909
    url: https://github.com/07prajwal2000
    slug: 07prajwal2000
