name: ci-for-cbe-blocks-package
on:
  push:
    branches:
      - main
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm install
      - name: Change Directory to blocks package
        run: cd packages/blocks
      - name: Run tests
        run: npm test
